name: &name "dqn-low-dim-dense"

agent:
  gamma: 0.99
  train_data:
    dataset:
      batch_size: 4

  env: 
    env_name: "CartPole-v0"

  exploration_scheduler:
    _target_: "drl.core.exploration.EpsilonGreeyExplorationScheduler"
    eps_start: 0.9
    eps_end: 0.1
    decay_factor: 1.0

  replay_buffer:
    capacity: 1000000

  network:
    encoder:
      _target_: "drl.blocks.encoder.dense_encoder.DenseEncoder"
      n_layers: 2
      input_dim: 4
      hidden_dim: 64
    output_head:
      _target_: "drl.blocks.heads.ValueHead"
      output_dim: 2
      hidden_dim: 64

  optimizer:
    _target_: "torch.optim.RMSprop"
    lr: 0.001

trainer:
  gpus: 0
  checkpoint_callback: true
  max_epochs: 20
  max_steps: 20000